import type { Monaco } from "@monaco-editor/react";

/// Shared Monaco theme used by both the file editor (EditorPane) and the
/// diff viewer (DiffEditorView). Ported from Dark Modern 2026
/// (icarogabryel/dark-modern-2026) with Dark+ token colors.
export const THEME_NAME = "treehouse-dark";

export function defineTreehouseTheme(monaco: Monaco) {
  monaco.editor.defineTheme(THEME_NAME, {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "6A9955", fontStyle: "italic" },
      { token: "comment.doc", foreground: "6A9955", fontStyle: "italic" },

      { token: "string", foreground: "CE9178" },
      { token: "string.escape", foreground: "D7BA7D" },
      { token: "string.key.json", foreground: "9CDCFE" },
      { token: "string.value.json", foreground: "CE9178" },
      { token: "regexp", foreground: "D16969" },

      { token: "keyword", foreground: "569CD6" },
      { token: "keyword.flow", foreground: "C586C0" },
      { token: "keyword.json", foreground: "569CD6" },
      { token: "keyword.operator", foreground: "D4D4D4" },
      { token: "storage", foreground: "569CD6" },
      { token: "storage.type", foreground: "569CD6" },

      { token: "number", foreground: "B5CEA8" },
      { token: "number.hex", foreground: "B5CEA8" },
      { token: "number.float", foreground: "B5CEA8" },
      { token: "constant", foreground: "4FC1FF" },
      { token: "constant.language", foreground: "569CD6" },

      { token: "type", foreground: "4EC9B0" },
      { token: "type.identifier", foreground: "4EC9B0" },
      { token: "namespace", foreground: "4EC9B0" },
      { token: "annotation", foreground: "DCDCAA" },

      { token: "identifier", foreground: "9CDCFE" },
      { token: "variable", foreground: "9CDCFE" },
      { token: "variable.parameter", foreground: "9CDCFE" },
      { token: "variable.predefined", foreground: "4FC1FF" },

      { token: "function", foreground: "DCDCAA" },
      { token: "support.function", foreground: "DCDCAA" },

      { token: "operator", foreground: "D4D4D4" },
      { token: "delimiter", foreground: "D4D4D4" },
      { token: "delimiter.bracket", foreground: "D4D4D4" },
      { token: "delimiter.parenthesis", foreground: "D4D4D4" },
      { token: "delimiter.square", foreground: "D4D4D4" },
      { token: "delimiter.curly", foreground: "D4D4D4" },

      { token: "tag", foreground: "569CD6" },
      { token: "tag.id", foreground: "569CD6" },
      { token: "metatag", foreground: "569CD6" },
      { token: "attribute.name", foreground: "9CDCFE" },
      { token: "attribute.value", foreground: "CE9178" },

      { token: "key", foreground: "9CDCFE" },
      { token: "type.yaml", foreground: "9CDCFE" },
      { token: "string.yaml", foreground: "CE9178" },
    ],
    colors: {
      "editor.background": "#121314",
      "editor.foreground": "#BBBEBF",
      "editorLineNumber.foreground": "#858889",
      "editorLineNumber.activeForeground": "#BBBEBF",
      "editor.lineHighlightBackground": "#242526",
      "editor.lineHighlightBorder": "#00000000",
      "editor.selectionBackground": "#276782dd",
      "editor.inactiveSelectionBackground": "#27678260",
      "editor.selectionHighlightBackground": "#27678260",
      "editor.wordHighlightBackground": "#27678250",
      "editor.wordHighlightStrongBackground": "#27678280",
      "editor.findMatchBackground": "#27678290",
      "editor.findMatchHighlightBackground": "#27678280",
      "editor.findRangeHighlightBackground": "#242526",
      "editor.hoverHighlightBackground": "#242526",
      "editor.rangeHighlightBackground": "#242526",
      "editorCursor.foreground": "#BBBEBF",
      "editorIndentGuide.background1": "#8384854D",
      "editorIndentGuide.activeBackground1": "#838485",
      "editorWhitespace.foreground": "#8C8C8C4D",
      "editorRuler.foreground": "#848484",
      "editorBracketMatch.background": "#3994BC55",
      "editorBracketMatch.border": "#2A2B2CFF",
      "editorGutter.background": "#121314",
      "editorGutter.addedBackground": "#72C892",
      "editorGutter.deletedBackground": "#F28772",
      "editorLink.activeForeground": "#3a94bc",
      "editorCodeLens.foreground": "#8C8C8C",
      "editorOverviewRuler.border": "#2A2B2CFF",
      "scrollbar.shadow": "#191B1D4D",
      "scrollbarSlider.background": "#83848533",
      "scrollbarSlider.hoverBackground": "#83848566",
      "scrollbarSlider.activeBackground": "#83848599",
      "minimapSlider.background": "#83848533",
      "minimapSlider.hoverBackground": "#83848566",
      "minimapSlider.activeBackground": "#83848599",
      "editorWidget.background": "#202122",
      "editorWidget.border": "#2A2B2CFF",
      "editorWidget.foreground": "#bfbfbf",
      "editorSuggestWidget.background": "#202122",
      "editorSuggestWidget.border": "#2A2B2CFF",
      "editorSuggestWidget.foreground": "#bfbfbf",
      "editorSuggestWidget.highlightForeground": "#bfbfbf",
      "editorSuggestWidget.selectedBackground": "#3994BC26",
      "editorHoverWidget.background": "#202122",
      "editorHoverWidget.border": "#2A2B2CFF",
      "input.background": "#191A1B",
      "input.border": "#333536FF",
      focusBorder: "#3994BCB3",
      "diffEditor.insertedLineBackground": "#347d3926",
      "diffEditor.insertedTextBackground": "#57ab5a4d",
      "diffEditor.removedLineBackground": "#c93c3726",
      "diffEditor.removedTextBackground": "#f470674d",
    },
  });
}
