// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse activity classification driven by time-since-last-output. The
 * sidebar polls `list_agent_activity` every ~1.5s and paints a dot.
 */
export type AgentActivity = "inactive" | "working" | "idle" | "needsAttention";
