// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sorted, deduped list of language ids the user has flipped on in
 * the cog menu. The IDs match `LspConfig::id` (e.g. `"rust"`,
 * `"cpp"`); built-in or custom doesn't matter — both share the same
 * on/off track. Empty list = nothing enabled (matches the previous
 * behavior, where seeded built-ins shipped `enabled = false`).
 *
 * Storage is `Vec<String>` rather than `BTreeSet<String>` purely so
 * JSON round-trips as a flat array — internally we treat it as a
 * set (sort + dedup at write time).
 * Per-backend default CLI command, pre-filled in the AgentPane launcher.
 * Stored as a full command line (binary + args); the frontend shell-splits
 * it into argv at launch. Defaults mirror `AgentBackendKind::default_argv`.
 */
export type AgentCommands = { claudeCode: string, codex: string, kiro: string, };
