// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStatus } from "./AgentStatus";

/**
 * Streamed over a per-session Tauri Channel returned from `launch_agent`.
 */
export type AgentEvent = { "kind": "data", bytes: Array<number>, } | { "kind": "status", status: AgentStatus, };
