// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentBackendKind } from "./AgentBackendKind";
import type { AgentSessionId } from "./AgentSessionId";
import type { AgentStatus } from "./AgentStatus";
import type { WorktreeId } from "./WorktreeId";

export type AgentSession = { id: AgentSessionId, worktreeId: WorktreeId, backend: AgentBackendKind, argv: Array<string>, 
/**
 * Unix epoch milliseconds.
 */
startedAt: bigint, cols: number, rows: number, status: AgentStatus, };
