// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPatterns } from "./AgentPatterns";

/**
 * The effective agent status patterns (built-in defaults filled in
 * for any backend the user hasn't customized) plus the list of
 * backends that *are* explicitly customized in `treehouse.toml` —
 * drives the per-backend "Reset to default" affordance.
 */
export type AgentPatternsView = { patterns: AgentPatterns, 
/**
 * camelCase backend keys (`claudeCode` / `kiro` / `codex`).
 */
customized: Array<string>, };
