// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppErrorKind } from "./AppErrorKind";

export type AppErrorPayload = { kind: AppErrorKind, message: string, };
