// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One named agent (sub-agent profile / context) the user can pre-select
 * when launching. Discovered by shelling out to the backend's CLI:
 * `claude agents list` or `kiro-cli agent list`. Codex has no analog.
 */
export type BackendAgent = { name: string, };
