// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One backend's attention + idle pattern lists. Substrings, not
 * regexes — keeps the per-chunk cost predictable and the format
 * readable for users editing `treehouse.toml`.
 */
export type BackendPatterns = { attention: Array<string>, idle: Array<string>, };
