// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One reviewer comment anchored to a (workspace_root, branch, file, line).
 * Stored as a flat list across all workspaces; frontend filters by the
 * pair `(workspace_root, branch)` since worktree IDs are ephemeral
 * across app restarts.
 */
export type Comment = { id: string, workspaceRoot: string, branch: string, filePath: string, line: number, text: string, 
/**
 * Epoch milliseconds. Fits in `Number.MAX_SAFE_INTEGER` for the next
 * ~285k years, so ts-rs is overridden to surface it as `number` rather
 * than `bigint` — BigInt args can't be sent over Tauri's IPC (which
 * `JSON.stringify`s arguments).
 */
createdAt: number, resolvedAt: number | null, };
