// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Worktree } from "./Worktree";

/**
 * What `create` returns: the worktree, plus an optional non-fatal warning
 * (e.g. submodule init failed). The worktree itself is alive on disk and
 * usable in either case.
 */
export type CreateWorktreeResult = { worktree: Worktree, warning: string | null, };
