// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffStats } from "./DiffStats";
import type { FileDiff } from "./FileDiff";
import type { WorktreeId } from "./WorktreeId";

export type DiffSet = { worktreeId: WorktreeId, baseRef: string, 
/**
 * Unix epoch milliseconds.
 */
computedAt: bigint, files: Array<FileDiff>, stats: DiffStats, 
/**
 * When true, file contents and hunks are elided (repo too large).
 */
truncated: boolean, };
