// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiffLine = { "kind": "ctx", content: string, } | { "kind": "add", content: string, } | { "kind": "del", content: string, };
