// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which view of the worktree's changes the user is asking for.
 * `Branch` is the default — everything since `merge-base(default,
 * branch)`, the GitHub PR-style "what would land if I merged this"
 * view. `Uncommitted` shows just `HEAD..workdir` — the agent's
 * most recent batch of edits, easier to review in isolation.
 */
export type DiffMode = "branch" | "uncommitted";
