// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileStatus } from "./FileStatus";
import type { Hunk } from "./Hunk";

export type FileDiff = { path: string, status: FileStatus, hunks: Array<Hunk>, binary: boolean, insertions: number, deletions: number, };
