// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileStatus = { "kind": "added" } | { "kind": "modified" } | { "kind": "deleted" } | { "kind": "renamed", from: string, } | { "kind": "untracked" };
