// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileContent = { 
/**
 * UTF-8 text if the file decodes cleanly. `None` for binary or invalid
 * UTF-8 — the frontend renders a "binary file" placeholder in that case.
 */
text: string | null, size: bigint, binary: boolean, };
