// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which forge a workspace's remote points at. `Unknown` = a remote we
 * couldn't classify (e.g. a self-managed host without "gitlab"/"github"
 * in the name) — the UI stays quiet rather than guessing.
 */
export type ForgeKind = "github" | "gitlab" | "unknown";
