// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForgeKind } from "./ForgeKind";

/**
 * Availability + auth of the forge CLI for a workspace. Always well-formed
 * (never errors) so the UI can render an "install / `glab auth login`" prompt.
 */
export type ForgeStatus = { kind: ForgeKind, host: string | null, 
/**
 * `glab`/`gh` is on PATH.
 */
installed: boolean, 
/**
 * `glab/gh auth status` exited cleanly.
 */
authenticated: boolean, };
