// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ForgeMr = { 
/**
 * GitHub PR number / GitLab MR iid.
 */
number: number, title: string, sourceBranch: string, targetBranch: string, 
/**
 * Normalized lowercase: "open" | "merged" | "closed".
 */
state: string, url: string, draft: boolean, 
/**
 * GitLab's `detailed_merge_status` — e.g. "mergeable",
 * "discussions_not_resolved", "ci_must_pass", "not_approved", "conflict".
 * Drives the "why can't I merge" hint. `None` when unknown.
 */
mergeStatus: string | null, };
