// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The current user's approval state for an MR/PR, so the UI can toggle
 * between Approve and Unapprove.
 */
export type ForgeApproval = { 
/**
 * The current user has approved this MR/PR.
 */
approved: boolean, 
/**
 * The current user is eligible to approve.
 */
canApprove: boolean, };
