// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ForgePipeline = { id: number, 
/**
 * Branch/ref the pipeline ran against.
 */
refName: string, sha: string, 
/**
 * GitLab: created|pending|running|success|failed|canceled|skipped.
 */
status: string, webUrl: string, createdAt: string, };
