// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ForgePosition = { newPath: string | null, newLine: number | null, oldPath: string | null, oldLine: number | null, };
