// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ForgeJob = { id: number, name: string, stage: string, status: string, 
/**
 * True for a superseded run (a later retry replaced it). The current run
 * of a job is `retried: false`. Retried runs are kept only so stage order
 * can be computed from the earliest job id per stage.
 */
retried: boolean, };
