// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForgeNote } from "./ForgeNote";

/**
 * One review/discussion thread on an MR/PR. `id` is the discussion id used
 * to target a threaded reply.
 */
export type ForgeThread = { id: string, notes: Array<ForgeNote>, 
/**
 * This discussion can be resolved (it has resolvable notes — i.e. it's a
 * review thread, not a plain system/general note).
 */
resolvable: boolean, 
/**
 * All resolvable notes in the discussion are resolved.
 */
resolved: boolean, };
