// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForgePosition } from "./ForgePosition";

export type ForgeNote = { id: number, author: string, body: string, 
/**
 * Present iff this is an inline (diff-anchored) note.
 */
position: ForgePosition | null, createdAt: string, };
