// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ForgeIssue = { 
/**
 * GitHub number / GitLab iid, normalized to one field.
 */
number: number, title: string, body: string, 
/**
 * Normalized lowercase: "open" | "closed".
 */
state: string, labels: Array<string>, assignees: Array<string>, url: string, 
/**
 * ISO-8601 passthrough.
 */
updatedAt: string, };
