// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HookFailure } from "./HookFailure";

/**
 * Result of running a hook chain inline (used by `on_destroy`,
 * where there's no live terminal tab to surface output). `failed`
 * carries `(step_name, reason)` for the renderer's toast.
 */
export type HookRunSummary = { ran: number, succeeded: number, failed: Array<HookFailure>, };
