// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One command in a hook chain. Used by both `on_create` (executed
 * in a renderer-mounted terminal tab so the user sees output live)
 * and `on_destroy` (executed inline on the Rust side, since the
 * worktree disappears mid-run).
 */
export type HookStep = { 
/**
 * Human label echoed before the command runs. Just for the user
 * reading the terminal output / trace logs; not used for logic.
 */
name: string, 
/**
 * Program to invoke (looked up on `$PATH`, or absolute).
 */
command: string, args: Array<string>, env: { [key in string]?: string }, };
