// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffLine } from "./DiffLine";

export type Hunk = { 
/**
 * Stable within a DiffSet — FNV hash of the hunk header + body.
 */
id: string, header: string, oldStart: number, oldLines: number, newStart: number, newLines: number, lines: Array<DiffLine>, };
