// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathMapping } from "./PathMapping";

/**
 * One language's configuration. Persisted in `languages.toml` under the
 * app config dir. Users flip `enabled`, we spawn; flip back, we kill.
 */
export type LspConfig = { 
/**
 * Stable slug. `"rust"`, `"typescript"`, etc. Used as the primary key.
 */
id: string, displayName: string, 
/**
 * Binary name (resolved via PATH) or absolute path.
 */
command: string, args: Array<string>, 
/**
 * Monaco language IDs this server claims (e.g. `["typescript",
 * "javascript"]` for typescript-language-server).
 */
filetypes: Array<string>, 
/**
 * Filenames to search for when resolving the workspace root, walking
 * up from the opened file toward the worktree root.
 */
rootMarkers: Array<string>, enabled: boolean, 
/**
 * Shown in a toast when `command` isn't on PATH.
 */
installHint: string | null, 
/**
 * Environment overrides for the server process. BTreeMap for stable
 * TOML output ordering.
 */
env: { [key in string]?: string }, 
/**
 * When set, install URI translation between host paths and the
 * LSP's view of the filesystem. Most useful for containerized
 * servers (devcontainer / docker exec / etc.). See `PathMapping`.
 */
pathMapping: PathMapping | null, };
