// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspServerStatus } from "./LspServerStatus";

/**
 * Streamed over a per-session Tauri Channel returned from `lsp_ensure`.
 * `Data` carries raw LSP frames (`Content-Length: N\r\n\r\n<json>`); the
 * renderer reassembles them via `vscode-jsonrpc`.
 */
export type LspEvent = { "kind": "data", bytes: Array<number>, } | { "kind": "stderr", text: string, } | { "kind": "status", status: LspServerStatus, };
