// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathMapping } from "./PathMapping";

/**
 * Partial language config. Anything `None` inherits from the global
 * `LspConfig` for the same language.
 */
export type LspOverride = { 
/**
 * Absolute host path of the workspace this override applies to
 * (the main clone — not a worktree). Applies to every worktree
 * of that workspace. Canonicalized at compare time so symlink /
 * trailing-slash variants still match.
 */
workspace: string, 
/**
 * Matches `LspConfig::id` (e.g. `"cpp"`).
 */
language: string, command: string | null, args: Array<string> | null, env: { [key in string]?: string } | null, pathMapping: PathMapping | null, };
