// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspServerId } from "./LspServerId";
import type { LspServerStatus } from "./LspServerStatus";
import type { PathMapping } from "./PathMapping";
import type { WorktreeId } from "./WorktreeId";

export type LspServerSession = { id: LspServerId, worktreeId: WorktreeId, languageId: string, 
/**
 * `file://` URL of the resolved workspace root passed to `initialize`.
 */
rootUri: string, argv: Array<string>, 
/**
 * Unix epoch milliseconds. `#[ts(type = "number")]` — fits safely in
 * JS Number and avoids Tauri's BigInt-in-IPC-args quirk, same trick
 * as `Comment::created_at`.
 */
startedAt: number, status: LspServerStatus, 
/**
 * Resolved path translation for this session, if any. Returned to
 * the renderer so it can install the URI-swapping JSON-RPC
 * middleware on the message connection. `None` means raw pass-through.
 */
pathMapping: PathMapping | null, };
