// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspServerId } from "./LspServerId";
import type { LspServerStatus } from "./LspServerStatus";
import type { WorktreeId } from "./WorktreeId";

export type LspServerSession = { id: LspServerId, worktreeId: WorktreeId, languageId: string, 
/**
 * `file://` URL of the resolved workspace root passed to `initialize`.
 */
rootUri: string, argv: Array<string>, 
/**
 * Unix epoch milliseconds. `#[ts(type = "number")]` — fits safely in
 * JS Number and avoids Tauri's BigInt-in-IPC-args quirk, same trick
 * as `Comment::created_at`.
 */
startedAt: number, status: LspServerStatus, };
