// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LspServerStatus = { "kind": "spawning" } | { "kind": "running" } | { "kind": "exited", code: number | null, } | { "kind": "crashed", message: string, } | { "kind": "notFound", command: string, hint: string | null, };
