// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MergeResult = { "kind": "clean" } | { "kind": "nothingToMerge", uncommittedChanges: boolean, } | { "kind": "conflict", message: string, } | { "kind": "wrongBranch", current: string, expected: string, };
