// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One command in the post-create chain. Steps run sequentially in a
 * single shell session — see the script-builder in the renderer for
 * how `&&` chaining + a final drop-into-shell are stitched together.
 */
export type OnCreateStep = { 
/**
 * Human label echoed before the command runs. Just for the user
 * reading the terminal output; not used for logic.
 */
name: string, 
/**
 * Program to invoke (looked up on `$PATH`, or absolute).
 */
command: string, args: Array<string>, env: { [key in string]?: string }, };
