// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filesystem-prefix translation for an LSP whose process sees a
 * different filesystem layout than the host (e.g. a containerized
 * clangd). At session-spawn time we install a JSON-RPC middleware
 * that swaps `file://${host_root}/…` ↔ `file://${remote_root}/…` on
 * every URI flowing through the connection. Host_root defaults to
 * the active worktree's absolute path when unset, so most configs
 * only need to set `remote_root`.
 */
export type PathMapping = { remoteRoot: string, hostRoot: string | null, };
