// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PtyEvent = { "kind": "data", 
/**
 * Raw PTY output bytes. Serialized as a JSON number array over the
 * Tauri Channel. Normal shell volumes are fine; if this becomes
 * a hotspot for long agent output, swap to base64 or Tauri's binary
 * channel mode.
 */
bytes: Array<number>, } | { "kind": "exit", code: number | null, };
