// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecentWorkspace = { path: string, 
/**
 * Unix epoch milliseconds of the most recent open.
 */
lastOpenedAt: bigint, };
