// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for a line-anchored review comment — mirrors the renderer's stored
 * `Comment` (filePath + line + text). The provider fetches the diff SHAs itself.
 */
export type ReviewCommentInput = { filePath: string, line: number, body: string, };
