// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentBackendKind } from "./AgentBackendKind";
import type { MergeBackStrategy } from "./MergeBackStrategy";
import type { SyncStrategy } from "./SyncStrategy";

/**
 * Sorted, deduped list of language ids the user has flipped on in
 * the cog menu. The IDs match `LspConfig::id` (e.g. `"rust"`,
 * `"cpp"`); built-in or custom doesn't matter — both share the same
 * on/off track. Empty list = nothing enabled (matches the previous
 * behavior, where seeded built-ins shipped `enabled = false`).
 *
 * Storage is `Vec<String>` rather than `BTreeSet<String>` purely so
 * JSON round-trips as a flat array — internally we treat it as a
 * set (sort + dedup at write time).
 */
export type Settings = { 
/**
 * Default strategy when the user clicks Sync. Defaults to Rebase
 * (linear agent-branch history; auto-aborts on conflict).
 */
syncStrategy: SyncStrategy, 
/**
 * Default strategy preselected in the Merge dialog. Defaults to
 * RebaseFf (rebase agent branch + ff-only merge — linear history).
 */
mergeBackStrategy: MergeBackStrategy, 
/**
 * When true, run `git submodule update --init --recursive` on the
 * new worktree after creation. Off by default — most repos don't have
 * submodules and the extra git invocation just slows create down.
 */
initSubmodules: boolean, 
/**
 * Which agent backend is preselected in the AgentPane's + New launcher.
 * Persisted so users who always reach for the same agent don't have
 * to reselect it on every new session.
 */
defaultAgentBackend: AgentBackendKind, 
/**
 * LSP languages the user has flipped on. See struct-level rustdoc.
 */
enabledLspLanguages: Array<string>, 
/**
 * Per-workspace base ref for the Changes (Branch-view) diff, keyed by
 * workspace root path. Absent key → the effective default of
 * `origin/<default_branch>`. Keyed by path rather than `WorkspaceId`
 * because IDs are regenerated on every app launch (see `Comment`).
 */
baseRefs: { [key in string]?: string }, };
