// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MergeBackStrategy } from "./MergeBackStrategy";
import type { SyncStrategy } from "./SyncStrategy";

export type Settings = { 
/**
 * Default strategy when the user clicks Sync. Defaults to Rebase
 * (linear agent-branch history; auto-aborts on conflict).
 */
syncStrategy: SyncStrategy, 
/**
 * Default strategy preselected in the Merge dialog. Defaults to
 * RebaseFf (rebase agent branch + ff-only merge — linear history).
 */
mergeBackStrategy: MergeBackStrategy, 
/**
 * UI zoom factor applied via `document.documentElement.style.zoom`
 * on the frontend. 1.0 = default. Clamped to [0.5, 2.0] on the
 * frontend; we persist whatever the user lands on.
 */
zoom: number, };
