// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncResult = { "kind": "clean", head: string, } | { "kind": "alreadyUpToDate" } | { "kind": "dirty" } | { "kind": "conflict", message: string, } | { "kind": "rebaseAborted", message: string, };
