// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalId } from "./TerminalId";
import type { WorktreeId } from "./WorktreeId";

export type TerminalSession = { id: TerminalId, worktreeId: WorktreeId, shell: string, cols: number, rows: number, alive: boolean, };
