// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TreeEntry = { name: string, 
/**
 * Worktree-relative path, forward-slash-separated on all platforms.
 */
path: string, isDir: boolean, 
/**
 * True iff this entry is covered by `.gitignore` or the built-in ignore
 * list — only meaningful when `list_tree` was called with
 * `show_ignored = true`, since ignored entries are otherwise filtered
 * out. The tree renders these dimmer so the user can tell what they're
 * looking at.
 */
ignored: boolean, };
