// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TreeEntry = { name: string, 
/**
 * Worktree-relative path, forward-slash-separated on all platforms.
 */
path: string, isDir: boolean, };
