// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentActivity } from "./AgentActivity";
import type { WorktreeId } from "./WorktreeId";

export type WorktreeActivity = { worktreeId: WorktreeId, activity: AgentActivity, 
/**
 * Commits on the worktree's branch not on the workspace's default branch.
 */
ahead: number, 
/**
 * Commits on the default branch not on the worktree's branch.
 */
behind: number, 
/**
 * `git status --porcelain` returned anything: tracked or untracked
 * changes exist in the worktree's workdir.
 */
dirty: boolean, 
/**
 * Branch's work is already represented on default (via merge, squash,
 * rebase, etc.) — detected by tree equality from `git merge-tree`.
 * Lets the sidebar drop squash-merged worktrees into "Inactive"
 * instead of stranding them under "Changes" forever.
 */
merged: boolean, };
