// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentActivity } from "./AgentActivity";
import type { WorktreeId } from "./WorktreeId";

export type WorktreeActivity = { worktreeId: WorktreeId, activity: AgentActivity, };
