// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-level hook entry — `workspace` scopes which repo it applies
 * to. (In-repo `.treehouse/worktree-setup.toml` is a separate file
 * with no `workspace` field; its scope is implicit.)
 *
 * `rename_all = "camelCase"` is a no-op for the current field names
 * (all single words) but matches the rest of the IPC surface and
 * guards future multi-word fields. Safe for TOML too, since none of
 * the keys actually change.
 */
export type WorktreeHookEntry = { workspace: string, name: string, command: string, args: Array<string>, env: { [key in string]?: string }, };
