// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceId } from "./WorkspaceId";

export type Workspace = { id: WorkspaceId, root: string, defaultBranch: string, 
/**
 * User-configured base ref for the Changes (Branch-view) diff, e.g.
 * `"origin/main"`. `None` → the effective default of
 * `origin/<default_branch>` (see `worktree::git_ops::effective_base`).
 * Persisted per workspace by root path in `Settings::base_refs` — worktree
 * IDs are ephemeral across restarts, so the config hangs off the repo.
 */
baseRefOverride: string | null, };
