// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorktreeHookEntry } from "./WorktreeHookEntry";

/**
 * The two worktree hook arrays from `treehouse.toml`, in IPC
 * (camelCase) shape.
 */
export type WorktreeHooks = { onCreate: Array<WorktreeHookEntry>, onDestroy: Array<WorktreeHookEntry>, };
