// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentActivity } from "./AgentActivity";
import type { WorktreeId } from "./WorktreeId";

export type WorktreeActivity = { worktreeId: WorktreeId, activity: AgentActivity, 
/**
 * Commits on the worktree's branch not on the workspace's default branch.
 */
ahead: number, 
/**
 * Commits on the default branch not on the worktree's branch.
 */
behind: number, };
