// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the sidebar actually needs per worktree. Stored in
 * `AppState::worktree_status` under the worktree's id.
 */
export type WorktreeStatus = { 
/**
 * Commits on this worktree's branch not on the workspace's default
 * branch (or `origin/<default>` when local is stale).
 */
ahead: number, 
/**
 * Commits on default not on this worktree's branch.
 */
behind: number, 
/**
 * `git status --porcelain` returned anything — tracked or untracked
 * changes exist in the workdir.
 */
dirty: boolean, 
/**
 * Branch's work is already represented on default (merge-tree equality).
 * Catches squash-merges that `ahead` alone can't see.
 */
merged: boolean, };
