// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceId } from "./WorkspaceId";

export type Workspace = { id: WorkspaceId, root: string, defaultBranch: string, };
